spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/Board
    username: ${mysql-account}
    password: ${mysql-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
